/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/free_-_skybox_anime_sky.glb 
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-anime-sky-56a60c1d1e8b44eabff138374f996d8f
Title: FREE - SkyBox Anime Sky
*/



/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/DarkMagicalLucid.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Skybox(props) {
  const { nodes, materials } = useGLTF('./models/DarkMagicalLucid1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Sphere.geometry} material={materials['Material.001']} scale={1000} />
    </group>
  )
}

useGLTF.preload('./models/DarkMagicalLucid1.glb')
  