/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 public/models/free_-_skybox_anime_sky.glb 
Author: Paul (https://sketchfab.com/paul_paul_paul)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-skybox-anime-sky-56a60c1d1e8b44eabff138374f996d8f
Title: FREE - SkyBox Anime Sky
*/

import React, { useLayoutEffect, useRef } from 'react'
import { useGLTF, useScroll } from '@react-three/drei'
import gsap from "gsap";
import { useFrame } from '@react-three/fiber';


export function Skybox(props) {
    const { nodes, materials } = useGLTF('./models/NightSkyLucidDreaming3.glb')
    return (
      <group {...props} dispose={null}>
        <group scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={[50000, 49999.992, 49999.992]}>
            <mesh geometry={nodes.Sphere__0.geometry} material={materials.Material} rotation={[-Math.PI, 0, -Math.PI]} scale={0.136} />
          </group>
        </group>
      </group>
    )
  }
  
  useGLTF.preload('./models/NightSkyLucidDreaming3.glb')
  